name = "toolkit-hub"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = "dist"

[env.production]
name = "toolkit-hub"

[env.production.vars]
VITE_TENOR_API_KEY = "AIzaSyCwd7X3s7kWwwAujYxJ1DUtk726UE2SNcM" 